- name: Check and create file if not exists
  hosts: all
  tasks:
    - name: Check if file exists
      stat:
        path: /etc/example.conf
      register: file_check

    - name: Create file if it does not exist
      file:
        path: /etc/example.conf
        state: touch
      when: not file_check.stat.exists
