- name: Install Docker and start container
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Run NGINX container
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
