- name: Gather system information, check uptime, and verify file existence
  hosts: all
  become: yes
  gather_facts: yes  # Enables fact gathering

  tasks:
    - name: Display basic system information
      debug:
        msg:
          - "Operating System: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Memory: {{ ansible_memtotal_mb }} MB"
          - "IP Address: {{ ansible_default_ipv4.address }}"

    - name: Check system uptime
      command: uptime
      register: uptime_output  # Register command output

    - name: Display system uptime
      debug:
        msg: "System uptime: {{ uptime_output.stdout }}"  # Access the registered variable

    - name: Check if /etc/passwd file exists
      stat:
        path: /etc/passwd
      register: passwd_file_stat  # Register stat output

    - name: Display if /etc/passwd exists
      debug:
        msg: "File /etc/passwd exists: {{ passwd_file_stat.stat.exists }}"

    - name: Create a backup if /etc/passwd exists
      copy:
        src: /etc/passwd
        dest: /tmp/passwd_backup
      when: passwd_file_stat.stat.exists  # Condition based on file existence