# Using Handlers to Restart Services

- name: Configure Apache
  hosts: web_servers
  become: yes
  tasks:
    - name: Update Apache configuration
      copy:
        src: apache_config.conf
        dest: /etc/httpd/conf/httpd.conf
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: httpd
        state: restarted

# # Configure NGINX as load balancer
# Template module is used to copy a Jinja2 template file (nginx.conf.j2) from the Ansible control node (the machine where you run Ansible) to the remote.
# Using a template lets you inject variables and logic into the configuration file.

    - name: Configure nginx.conf
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart NGINX

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
