# This Dockerfile demonstrates various commands: FROM, ENV, WORKDIR, COPY, RUN, CMD, and ENTRYPOINT.

FROM ubuntu:latest

ENV APP_HOME /usr/src/app
ENV APP_ENV /production

WORKDIR $APP_HOME

COPY . .

RUN apt-get install && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/list/* 

CMD ["echo" "Hello Docker"]

ENTRYPOINT ["echo" "Running in " "$APP_ENV"]